### ISSUE TITLE
Shortcut to button?

### ISSUE THREAD

**Issue by nurpis** [maroun-baydoun/youtube-controller-extension#1]
Really nice extension!
But is there any possibility to add a shortcut to the button? It could be something like ctrl + p (play/pause) and if you have multiple youtube sessions, you just add a number to choose session: ctrl + p + 1.

If the shortcut could be global (so you don't need chrome to be active) it would be awesome :) But problems may of course occur if you have multiple chrome windows opened..

**Comment by maroun-baydoun** [comment]
Thank you!

I guess the first suggestion is totally feasible.

As for the second suggestion, it could be complicated to implement.
