### ISSUE TITLE
No longer working with Chrome 91

### ISSUE THREAD

**Issue by orschiro** [maroun-baydoun/youtube-controller-extension#26]
@maroun-baydoun this is a wonderful extension!

Sadly it stopped working with Chrome 91. 

Can you confirm?

Thanks!

**Comment by maroun-baydoun** [comment]
Hi @orschiro 

It seems to be working for me. Could you explain what's not working in your case?

**Comment by orschiro** [comment]
Never mind, user error.

Thanks for this great extension!

Maroun Baydoun ***@***.***> schrieb am So., 6. Juni 2021,
00:00:
